### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LuXX6666** [katerinakazantseva/MetagenomeStrainy_ONT_pipeline#1]
snakemake --snakefil snakemake --cores 30 --use-conda -n

Traceback (most recent call last):

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2077, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 334, in dag
    return DAGApi(
           ^^^^^^^

  File "<string>", line 6, in __init__

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 439, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 386, in _workflow
    workflow.include(

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1444, in include
    code, rulecount = parse(
                      ^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 1310, in parse
    for t, orig_token in automaton.consume():
                         ^^^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 144, in consume
    for t, orig in self.state(token):
                   ^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 1252, in python
    for t in self.subautomaton(token.string, token=token).consume():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 144, in consume
    for t, orig in self.state(token):
                   ^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 342, in register_tag
    self.error(

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/parser.py", line 164, in error
    raise SyntaxError(msg, (self.snakefile.path, lineno(token), None, None))

  File "/ddnstor/imau_sunzhihong/imau_zhongz/03_work/09_time_nanopore/08_strainy_haplotype/MetagenomeStrainy_ONT_pipeline/snakemake", line 4

SyntaxError: Expected name or colon after storage keyword. The keyword storage has a special meaning in Snakemake. If you named a variable or function like this, please rename it to avoid the conflict.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2237, in main
    success = args_to_api(args, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2211, in args_to_api
    snakemake_api.print_exception(e)

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/api.py", line 239, in print_exception
    print_exception(ex, linemaps)

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/exceptions.py", line 96, in print_exception
    format_error(

  File "/home/imau_zhongz/01_software/01_conda/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/exceptions.py", line 20, in format_error
    lineno = linemaps[snakefile][lineno]
             ~~~~~~~~~~~~~~~~~~~^^^^^^^^

KeyError: 4

**Comment by LuXX6666** [comment]
snakemake

import re
import subprocess
from pytools.persistent_dict import PersistentDict
storage = PersistentDict("mystorage")



#Parameters

#ONT r_'eads path (.fq)
input_reads="/home/imau_zhongz/03_work/09_time_nanopore/03_rmhost/H13C.rmhosted.fq.gz"

#Flye path
flye_path="~/01_software/01_conda/miniconda3/envs/flye/bin/flye"

#Conda envs path (i.e "~/miniconda3/envs/")
conda_path="~/01_software/01_conda/miniconda3/envs/"

#Strainy path
strainy_path="~/01_software/01_conda/miniconda3/envs/strainy/bin/strainy"


#Clair model path (r1041_e82_400bps_sup_v420 is recomended)
clair_model_path="~/01_software/01_conda/miniconda3/envs/clair3/bin/clair/bin/"

**Comment by LuXX6666** [comment]
snakemake

import re
import subprocess
from pytools.persistent_dict import PersistentDict
storage = PersistentDict("mystorage")



#Parameters

#ONT r_'eads path (.fq)
input_reads="/home/imau_zhongz/03_work/09_time_nanopore/03_rmhost/H13C.rmhosted.fq.gz"

#Flye path
flye_path="~/01_software/01_conda/miniconda3/envs/flye/bin/flye"

#Conda envs path (i.e "~/miniconda3/envs/")
conda_path="~/01_software/01_conda/miniconda3/envs/"

#Strainy path
strainy_path="~/01_software/01_conda/miniconda3/envs/strainy/bin/strainy"


#Clair model path (r1041_e82_400bps_sup_v420 is recomended)
clair_model_path="~/01_software/01_conda/miniconda3/envs/clair3/bin/clair/bin/"
